package net.radzratz.eternalores.datagen;

import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.tags.BlockTags;
import net.neoforged.neoforge.common.Tags;
import net.neoforged.neoforge.common.data.BlockTagsProvider;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import net.radzratz.eternalores.EternalOres;
import net.radzratz.eternalores.block.EternalGeneralBlocks;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

public class EternalBlockTagProvider extends BlockTagsProvider {
    public EternalBlockTagProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider, @Nullable ExistingFileHelper existingFileHelper) {
        super(output, lookupProvider, EternalOres.MOD_ID, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.@NotNull Provider provider) {

        System.out.println("Loading Block Tags");


            //Ores Tag
            tag(Tags.Blocks.ORES)
                    .add(EternalGeneralBlocks.ALUMINUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_ALUMINUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.AMBER_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_AMBER_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.APATITE_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_APATITE_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.CINNABAR_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_CINNABAR_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.COBALT_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_COBALT_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.FLUORITE_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_FLUORITE_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.LEAD_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_LEAD_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.NICKEL_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_NICKEL_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.NITER_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_NITER_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.ONYX_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_ONYX_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.OSMIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_OSMIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.PLATINUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_PLUTONIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.PLUTONIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_PLATINUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.RUBY_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_RUBY_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.SAPPHIRE_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_SAPPHIRE_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.SULFUR_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_SULFUR_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.TIN_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_TIN_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.URANIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_URANIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.SILVER_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_SILVER_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.ZINC_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_ZINC_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.GALLIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_GALLIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.PERIDOT_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_PERIDOT_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.OBSIDIAN_ORE_BLOCK.get());

            //Ores in Ground Stone
            tag(Tags.Blocks.ORES_IN_GROUND_STONE)
                    .add(EternalGeneralBlocks.ALUMINUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.AMBER_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.APATITE_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.CINNABAR_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.COBALT_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.FLUORITE_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.LEAD_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.NICKEL_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.NITER_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.ONYX_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.OSMIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.PLATINUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.PLUTONIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.RUBY_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.SAPPHIRE_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.SULFUR_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.TIN_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.URANIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.SILVER_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.ZINC_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.GALLIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.PERIDOT_ORE_BLOCK.get());

            //Ores in Ground Deepslate
            tag(Tags.Blocks.ORES_IN_GROUND_DEEPSLATE)
                    .add(EternalGeneralBlocks.DEEPSLATE_ALUMINUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_AMBER_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_APATITE_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_CINNABAR_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_COBALT_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_FLUORITE_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_LEAD_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_NICKEL_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_NITER_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_ONYX_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_OSMIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_PLUTONIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_PLATINUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_RUBY_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_SAPPHIRE_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_SULFUR_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_TIN_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_URANIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_SILVER_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_ZINC_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_GALLIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_PERIDOT_ORE_BLOCK.get());

            //Ores in Ground Netherrack
            tag(Tags.Blocks.ORES_IN_GROUND_NETHERRACK)
                    .add(EternalGeneralBlocks.OBSIDIAN_ORE_BLOCK.get());

            //Storage Blocks
            tag(Tags.Blocks.STORAGE_BLOCKS)
                    .add(EternalGeneralBlocks.ALUMINUM_BLOCK.get())
                    .add(EternalGeneralBlocks.BRONZE_BLOCK.get())
                    .add(EternalGeneralBlocks.COBALT_BLOCK.get())
                    .add(EternalGeneralBlocks.ELECTRUM_BLOCK.get())
                    .add(EternalGeneralBlocks.ENDERIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.INVAR_BLOCK.get())
                    .add(EternalGeneralBlocks.LEAD_BLOCK.get())
                    .add(EternalGeneralBlocks.LUMIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.NICKEL_BLOCK.get())
                    .add(EternalGeneralBlocks.OSMIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.PLATINUM_BLOCK.get())
                    .add(EternalGeneralBlocks.PLUTONIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.TIN_BLOCK.get())
                    .add(EternalGeneralBlocks.SIGNALUM_BLOCK.get())
                    .add(EternalGeneralBlocks.ULTIMATITANIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.URANIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.SILVER_BLOCK.get())
                    .add(EternalGeneralBlocks.GRAPHITE_BLOCK.get())
                    .add(EternalGeneralBlocks.CONSTANTAN_BLOCK.get())
                    .add(EternalGeneralBlocks.BRASS_BLOCK.get())
                    .add(EternalGeneralBlocks.ZINC_BLOCK.get())
                    .add(EternalGeneralBlocks.STEEL_BLOCK.get())
                    .add(EternalGeneralBlocks.BLUE_STEEL_BLOCK.get())
                    .add(EternalGeneralBlocks.GALLIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.TITANIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.PEWTER_BLOCK.get())
                    .add(EternalGeneralBlocks.ROSE_GOLD_BLOCK.get())
                    .add(EternalGeneralBlocks.BRITANNIA_SILVER_BLOCK.get())

                    //GEM BLOCKS
                    .add(EternalGeneralBlocks.SAPPHIRE_BLOCK.get())
                    .add(EternalGeneralBlocks.FLUORITE_BLOCK.get())
                    .add(EternalGeneralBlocks.APATITE_BLOCK.get())
                    .add(EternalGeneralBlocks.CINNABAR_BLOCK.get())
                    .add(EternalGeneralBlocks.AMBER_BLOCK.get())
                    .add(EternalGeneralBlocks.ONYX_BLOCK.get())
                    .add(EternalGeneralBlocks.NITER_BLOCK.get())
                    .add(EternalGeneralBlocks.RUBY_BLOCK.get())
                    .add(EternalGeneralBlocks.PERIDOT_BLOCK.get())

                    //RAW ORE BLOCKS
                    .add(EternalGeneralBlocks.RAW_ALUMINUM_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_COBALT_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_LEAD_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_NICKEL_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_OSMIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_PLATINUM_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_PLUTONIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_SILVER_BLOCK.get())
                    .add(EternalGeneralBlocks.SULFUR_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_TIN_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_URANIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_ZINC_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_GALLIUM_BLOCK.get());

            //PICKAXE TAGS
            tag(BlockTags.MINEABLE_WITH_PICKAXE)
                    //ORE BLOCKS
                    .add(EternalGeneralBlocks.ALUMINUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_ALUMINUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.AMBER_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_AMBER_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.APATITE_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_APATITE_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.CINNABAR_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_CINNABAR_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.COBALT_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_COBALT_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.FLUORITE_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_FLUORITE_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.LEAD_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_LEAD_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.NICKEL_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_NICKEL_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.NITER_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_NITER_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.ONYX_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_ONYX_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.OSMIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_OSMIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.PLATINUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_PLUTONIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.PLUTONIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_PLATINUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.RUBY_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_RUBY_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.SAPPHIRE_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_SAPPHIRE_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.SULFUR_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_SULFUR_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.TIN_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_TIN_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.URANIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_URANIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.SILVER_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_SILVER_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.ZINC_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_ZINC_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.GALLIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_GALLIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.PERIDOT_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_PERIDOT_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.OBSIDIAN_ORE_BLOCK.get())

                    //METAL BLOCKS
                    .add(EternalGeneralBlocks.ALUMINUM_BLOCK.get())
                    .add(EternalGeneralBlocks.BRONZE_BLOCK.get())
                    .add(EternalGeneralBlocks.COBALT_BLOCK.get())
                    .add(EternalGeneralBlocks.ELECTRUM_BLOCK.get())
                    .add(EternalGeneralBlocks.ENDERIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.INVAR_BLOCK.get())
                    .add(EternalGeneralBlocks.LEAD_BLOCK.get())
                    .add(EternalGeneralBlocks.LUMIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.NICKEL_BLOCK.get())
                    .add(EternalGeneralBlocks.OSMIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.PLATINUM_BLOCK.get())
                    .add(EternalGeneralBlocks.PLUTONIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.TIN_BLOCK.get())
                    .add(EternalGeneralBlocks.SIGNALUM_BLOCK.get())
                    .add(EternalGeneralBlocks.ULTIMATITANIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.URANIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.SILVER_BLOCK.get())
                    .add(EternalGeneralBlocks.GRAPHITE_BLOCK.get())
                    .add(EternalGeneralBlocks.CONSTANTAN_BLOCK.get())
                    .add(EternalGeneralBlocks.BRASS_BLOCK.get())
                    .add(EternalGeneralBlocks.ZINC_BLOCK.get())
                    .add(EternalGeneralBlocks.STEEL_BLOCK.get())
                    .add(EternalGeneralBlocks.BLUE_STEEL_BLOCK.get())
                    .add(EternalGeneralBlocks.GALLIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.TITANIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.PEWTER_BLOCK.get())
                    .add(EternalGeneralBlocks.ROSE_GOLD_BLOCK.get())
                    .add(EternalGeneralBlocks.BRITANNIA_SILVER_BLOCK.get())

                    //GEM BLOCKS
                    .add(EternalGeneralBlocks.SAPPHIRE_BLOCK.get())
                    .add(EternalGeneralBlocks.FLUORITE_BLOCK.get())
                    .add(EternalGeneralBlocks.APATITE_BLOCK.get())
                    .add(EternalGeneralBlocks.CINNABAR_BLOCK.get())
                    .add(EternalGeneralBlocks.AMBER_BLOCK.get())
                    .add(EternalGeneralBlocks.ONYX_BLOCK.get())
                    .add(EternalGeneralBlocks.NITER_BLOCK.get())
                    .add(EternalGeneralBlocks.RUBY_BLOCK.get())
                    .add(EternalGeneralBlocks.PERIDOT_BLOCK.get())

                    //RAW ORE BLOCKS
                    .add(EternalGeneralBlocks.RAW_ALUMINUM_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_COBALT_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_LEAD_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_NICKEL_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_OSMIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_PLATINUM_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_PLUTONIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_SILVER_BLOCK.get())
                    .add(EternalGeneralBlocks.SULFUR_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_TIN_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_URANIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_ZINC_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_GALLIUM_BLOCK.get());

            tag(BlockTags.NEEDS_STONE_TOOL)
                    .add(EternalGeneralBlocks.ALUMINUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_ALUMINUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.TIN_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_TIN_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.SULFUR_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_SULFUR_ORE_BLOCK.get());

            tag(BlockTags.NEEDS_IRON_TOOL)
                    //ORE BLOCKS
                    .add(EternalGeneralBlocks.AMBER_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_AMBER_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.APATITE_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_APATITE_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.CINNABAR_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_CINNABAR_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.FLUORITE_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_FLUORITE_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.LEAD_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_LEAD_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.NICKEL_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_NICKEL_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.NITER_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_NITER_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.ONYX_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_ONYX_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.OSMIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_OSMIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.RUBY_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_RUBY_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.SAPPHIRE_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_SAPPHIRE_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.SILVER_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_SILVER_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.ZINC_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_ZINC_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.GALLIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_GALLIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.PERIDOT_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_PERIDOT_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.URANIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_URANIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.PLATINUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_PLATINUM_ORE_BLOCK.get())

                    //METAL BLOCKS
                    .add(EternalGeneralBlocks.ALUMINUM_BLOCK.get())
                    .add(EternalGeneralBlocks.BRONZE_BLOCK.get())
                    .add(EternalGeneralBlocks.COBALT_BLOCK.get())
                    .add(EternalGeneralBlocks.ELECTRUM_BLOCK.get())
                    .add(EternalGeneralBlocks.ENDERIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.INVAR_BLOCK.get())
                    .add(EternalGeneralBlocks.LEAD_BLOCK.get())
                    .add(EternalGeneralBlocks.LUMIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.NICKEL_BLOCK.get())
                    .add(EternalGeneralBlocks.OSMIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.PLATINUM_BLOCK.get())
                    .add(EternalGeneralBlocks.PLUTONIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.TIN_BLOCK.get())
                    .add(EternalGeneralBlocks.SIGNALUM_BLOCK.get())
                    .add(EternalGeneralBlocks.ULTIMATITANIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.URANIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.SILVER_BLOCK.get())
                    .add(EternalGeneralBlocks.GRAPHITE_BLOCK.get())
                    .add(EternalGeneralBlocks.CONSTANTAN_BLOCK.get())
                    .add(EternalGeneralBlocks.BRASS_BLOCK.get())
                    .add(EternalGeneralBlocks.ZINC_BLOCK.get())
                    .add(EternalGeneralBlocks.STEEL_BLOCK.get())
                    .add(EternalGeneralBlocks.BLUE_STEEL_BLOCK.get())
                    .add(EternalGeneralBlocks.GALLIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.TITANIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.PEWTER_BLOCK.get())
                    .add(EternalGeneralBlocks.ROSE_GOLD_BLOCK.get())
                    .add(EternalGeneralBlocks.BRITANNIA_SILVER_BLOCK.get())

                    //GEM BLOCKS
                    .add(EternalGeneralBlocks.SAPPHIRE_BLOCK.get())
                    .add(EternalGeneralBlocks.FLUORITE_BLOCK.get())
                    .add(EternalGeneralBlocks.APATITE_BLOCK.get())
                    .add(EternalGeneralBlocks.CINNABAR_BLOCK.get())
                    .add(EternalGeneralBlocks.AMBER_BLOCK.get())
                    .add(EternalGeneralBlocks.ONYX_BLOCK.get())
                    .add(EternalGeneralBlocks.NITER_BLOCK.get())
                    .add(EternalGeneralBlocks.RUBY_BLOCK.get())
                    .add(EternalGeneralBlocks.PERIDOT_BLOCK.get())

                    //RAW ORE BLOCKS
                    .add(EternalGeneralBlocks.RAW_ALUMINUM_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_COBALT_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_LEAD_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_NICKEL_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_OSMIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_PLATINUM_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_PLUTONIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_SILVER_BLOCK.get())
                    .add(EternalGeneralBlocks.SULFUR_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_TIN_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_URANIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_GALLIUM_BLOCK.get())
                    .add(EternalGeneralBlocks.RAW_ZINC_BLOCK.get());

            tag(BlockTags.NEEDS_DIAMOND_TOOL)
                    .add(EternalGeneralBlocks.COBALT_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_COBALT_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.PLUTONIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.DEEPSLATE_PLUTONIUM_ORE_BLOCK.get())
                    .add(EternalGeneralBlocks.OBSIDIAN_ORE_BLOCK.get());

    }
}
