package net.radzratz.eternalores.util.config;

import net.neoforged.neoforge.common.ModConfigSpec;
import net.radzratz.eternalores.util.config.util.EOMaterialConfigHelper;
import org.apache.commons.lang3.tuple.Pair;

public class EOMaterialConfig {
    public static final EOMaterialConfig CFG;
    public static final ModConfigSpec CONFIG_SPEC;

    public final EOMaterialConfigHelper EOAluminumSet;
    public final EOMaterialConfigHelper EOAlumiteSet;
    public final EOMaterialConfigHelper EOAmberSet;
    public final EOMaterialConfigHelper EOAmericiumSet;
    public final EOMaterialConfigHelper EOAmethystSet;
    public final EOMaterialConfigHelper EOAndesiteSet;
    public final EOMaterialConfigHelper EOAnnealedCopperSet;
    public final EOMaterialConfigHelper EOAnthraciteCoalSet;
    public final EOMaterialConfigHelper EOAntimatterSet;
    public final EOMaterialConfigHelper EOApatiteSet;
    public final EOMaterialConfigHelper EOArcanumSet;
    public final EOMaterialConfigHelper EOArditeSet;
    public final EOMaterialConfigHelper EOArmadilloSet;
    public final EOMaterialConfigHelper EOAuroriumSet;
    public final EOMaterialConfigHelper EOBasaltSet;
    public final EOMaterialConfigHelper EOBatteryAlloySet;
    public final EOMaterialConfigHelper EOBerylliumSet;
    public final EOMaterialConfigHelper EOBiomassSet;
    public final EOMaterialConfigHelper EOBiosteelSet;
    public final EOMaterialConfigHelper EOBismuthSet;
    public final EOMaterialConfigHelper EOBituminousCoalSet;
    public final EOMaterialConfigHelper EOBlackBronzeSet;
    public final EOMaterialConfigHelper EOBlackQuartzSet;
    public final EOMaterialConfigHelper EOBlackSteelSet;
    public final EOMaterialConfigHelper EOBlackstoneSet;
    public final EOMaterialConfigHelper EOBlazeSet;
    public final EOMaterialConfigHelper EOBlueSteelSet;
    public final EOMaterialConfigHelper EOBrassSet;
    public final EOMaterialConfigHelper EOBrickSet;
    public final EOMaterialConfigHelper EOBritanniaSilverSet;
    public final EOMaterialConfigHelper EOBronzeSet;
    public final EOMaterialConfigHelper EOCadmiumSet;
    public final EOMaterialConfigHelper EOCalciumSet;
    public final EOMaterialConfigHelper EOCalciteSet;
    public final EOMaterialConfigHelper EOCaliforniumSet;
    public final EOMaterialConfigHelper EOCatalyriumSet;
    public final EOMaterialConfigHelper EOCastIronSet;
    public final EOMaterialConfigHelper EOCastSteelSet;
    public final EOMaterialConfigHelper EOCarbonBlend;
    public final EOMaterialConfigHelper EOCeriumSet;
    public final EOMaterialConfigHelper EOCertusQuartzSet;
    public final EOMaterialConfigHelper EOCesiumSet;
    public final EOMaterialConfigHelper EOCharcoalSet;
    public final EOMaterialConfigHelper EOCinnabarSet;
    public final EOMaterialConfigHelper EOClaySet;
    public final EOMaterialConfigHelper EOCoalSet;
    public final EOMaterialConfigHelper EOCobaltSet;
    public final EOMaterialConfigHelper EOCokeSet;
    public final EOMaterialConfigHelper EOConstantanSet;
    public final EOMaterialConfigHelper EOCopperSet;
    public final EOMaterialConfigHelper EOCosmicMatterSet;
    public final EOMaterialConfigHelper EOChromiumSet;
    public final EOMaterialConfigHelper EOCrystallineAlloySet;
    public final EOMaterialConfigHelper EOCupronickelSet;
    public final EOMaterialConfigHelper EODeepslateSet;
    public final EOMaterialConfigHelper EODiamondSet;
    public final EOMaterialConfigHelper EODioriteSet;
    public final EOMaterialConfigHelper EODripstoneSet;
    public final EOMaterialConfigHelper EODustSet;
    public final EOMaterialConfigHelper EOElectrumSet;
    public final EOMaterialConfigHelper EOEmeraldSet;
    public final EOMaterialConfigHelper EOEnergeticBlendSet;
    public final EOMaterialConfigHelper EOEnderEyeSet;
    public final EOMaterialConfigHelper EOEndergeticSet;
    public final EOMaterialConfigHelper EOEnderPearlSet;
    public final EOMaterialConfigHelper EOEnderiumSet;
    public final EOMaterialConfigHelper EOEndstoneSet;
    public final EOMaterialConfigHelper EOEnergeticSilverSet;
    public final EOMaterialConfigHelper EOEternalDarkSet;
    public final EOMaterialConfigHelper EOEternalLightSet;
    public final EOMaterialConfigHelper EOEternitySet;
    public final EOMaterialConfigHelper EOEtheriumSet;
    public final EOMaterialConfigHelper EOExoticMatterSet;
    public final EOMaterialConfigHelper EOFlintSet;
    public final EOMaterialConfigHelper EOFluixSet;
    public final EOMaterialConfigHelper EOFluoriteSet;
    public final EOMaterialConfigHelper EOFranciumSet;
    public final EOMaterialConfigHelper EOGalliumSet;
    public final EOMaterialConfigHelper EOGarnetSet;
    public final EOMaterialConfigHelper EOGoldSet;
    public final EOMaterialConfigHelper EOGraphiteSet;
    public final EOMaterialConfigHelper EOGraniteSet;
    public final EOMaterialConfigHelper EOGravelSet;
    public final EOMaterialConfigHelper EOGravitroniumSet;
    public final EOMaterialConfigHelper EOHCarbonBlend;
    public final EOMaterialConfigHelper EOHafniumSet;
    public final EOMaterialConfigHelper EOHepatizonSet;
    public final EOMaterialConfigHelper EOIndiumSet;
    public final EOMaterialConfigHelper EOInvarSet;
    public final EOMaterialConfigHelper EOIridiumSet;
    public final EOMaterialConfigHelper EOIronSet;
    public final EOMaterialConfigHelper EOJadeSet;
    public final EOMaterialConfigHelper EOKanthalSet;
    public final EOMaterialConfigHelper EOLapisSet;
    public final EOMaterialConfigHelper EOLCarbonBlend;
    public final EOMaterialConfigHelper EOLeadSet;
    public final EOMaterialConfigHelper EOLigniteCoalSet;
    public final EOMaterialConfigHelper EOLumiumSet;
    public final EOMaterialConfigHelper EOMagnesiumSet;
    public final EOMaterialConfigHelper EOManganeseSet;
    public final EOMaterialConfigHelper EOMelodicAlloySet;
    public final EOMaterialConfigHelper EOMissingSet;
    public final EOMaterialConfigHelper EOModulariumSet;
    public final EOMaterialConfigHelper EOMolybdenumSet;
    public final EOMaterialConfigHelper EOMonaziteSet;
    public final EOMaterialConfigHelper EOMorphiteSet;
    public final EOMaterialConfigHelper EONaniteSet;
    public final EOMaterialConfigHelper EONautilusSet;
    public final EOMaterialConfigHelper EONecroticariteSet;
    public final EOMaterialConfigHelper EONeptuniumSet;
    public final EOMaterialConfigHelper EONetherBlendSet;
    public final EOMaterialConfigHelper EONetherBrickSet;
    public final EOMaterialConfigHelper EONetherStarSet;
    public final EOMaterialConfigHelper EONetherWartSet;
    public final EOMaterialConfigHelper EONetheriteSet;
    public final EOMaterialConfigHelper EONetherrackSet;
    public final EOMaterialConfigHelper EONethersteelSet;
    public final EOMaterialConfigHelper EONeodymiumSet;
    public final EOMaterialConfigHelper EONickelSet;
    public final EOMaterialConfigHelper EONiobiumSet;
    public final EOMaterialConfigHelper EONiterSet;
    public final EOMaterialConfigHelper EONovalloySet;
    public final EOMaterialConfigHelper EOsgloglasSet;
    public final EOMaterialConfigHelper EObsidianSet;
    public final EOMaterialConfigHelper EOOsmiumSet;
    public final EOMaterialConfigHelper EOnyxSet;
    public final EOMaterialConfigHelper EOPalladiumSet;
    public final EOMaterialConfigHelper EOPeatCoalSet;
    public final EOMaterialConfigHelper EOPearlSet;
    public final EOMaterialConfigHelper EOPeridotSet;
    public final EOMaterialConfigHelper EOPewterSet;
    public final EOMaterialConfigHelper EOPhantomMembraneSet;
    public final EOMaterialConfigHelper EOPhosphorusSet;
    public final EOMaterialConfigHelper EOPigIronSet;
    public final EOMaterialConfigHelper EOPlatinumSet;
    public final EOMaterialConfigHelper EOPlutoniumSet;
    public final EOMaterialConfigHelper EOPrimorniumSet;
    public final EOMaterialConfigHelper EOPrismarineSet;
    public final EOMaterialConfigHelper EOPurpurSet;
    public final EOMaterialConfigHelper EOPyroliteSet;
    public final EOMaterialConfigHelper EOQuantiquariteSet;
    public final EOMaterialConfigHelper EOQuartzSet;
    public final EOMaterialConfigHelper EOQuartzEnrichedCopperSet;
    public final EOMaterialConfigHelper EOQuartzEnrichedIronSet;
    public final EOMaterialConfigHelper EORareEarthSet;
    public final EOMaterialConfigHelper EORedstoneSet;
    public final EOMaterialConfigHelper EORedSandSet;
    public final EOMaterialConfigHelper EORedSteelSet;
    public final EOMaterialConfigHelper EORhodiumSet;
    public final EOMaterialConfigHelper EORoseGoldSet;
    public final EOMaterialConfigHelper EORottenFleshSet;
    public final EOMaterialConfigHelper EORubidiumSet;
    public final EOMaterialConfigHelper EORubySet;
    public final EOMaterialConfigHelper EORutheniumSet;
    public final EOMaterialConfigHelper EOSaltSet;
    public final EOMaterialConfigHelper EOSamariumSet;
    public final EOMaterialConfigHelper EOSandSet;
    public final EOMaterialConfigHelper EOSanguisVivusSet;
    public final EOMaterialConfigHelper EOSapphireSet;
    public final EOMaterialConfigHelper EOSculkSet;
    public final EOMaterialConfigHelper EOSculkiteSet;
    public final EOMaterialConfigHelper EOSeleniumSet;
    public final EOMaterialConfigHelper EOShadowBlendSet;
    public final EOMaterialConfigHelper EOShadowsteelSet;
    public final EOMaterialConfigHelper EOShulkerSet;
    public final EOMaterialConfigHelper EOSignalumSet;
    public final EOMaterialConfigHelper EOSiliconSet;
    public final EOMaterialConfigHelper EOSilverSet;
    public final EOMaterialConfigHelper EOSoulSandSet;
    public final EOMaterialConfigHelper EOSourceSet;
    public final EOMaterialConfigHelper EOSpectralSkyBlueriteSet;
    public final EOMaterialConfigHelper EOSpinelSet;
    public final EOMaterialConfigHelper EOStainlessSteelSet;
    public final EOMaterialConfigHelper EOStellariumSet;
    public final EOMaterialConfigHelper EOStellarAlloySet;
    public final EOMaterialConfigHelper EOSteelSet;
    public final EOMaterialConfigHelper EOStoneSet;
    public final EOMaterialConfigHelper EOStrangeMatterSet;
    public final EOMaterialConfigHelper EOSugarSet;
    public final EOMaterialConfigHelper EOSulfurSet;
    public final EOMaterialConfigHelper EOTachyariteSet;
    public final EOMaterialConfigHelper EOTantalumSet;
    public final EOMaterialConfigHelper EOTanzaniteSet;
    public final EOMaterialConfigHelper EOTemictetlSet;
    public final EOMaterialConfigHelper EOTinSet;
    public final EOMaterialConfigHelper EOTitaniumSet;
    public final EOMaterialConfigHelper EOTuffSet;
    public final EOMaterialConfigHelper EOTungstenSet;
    public final EOMaterialConfigHelper EOTurtleSet;
    public final EOMaterialConfigHelper EOUnstableIngotSet;
    public final EOMaterialConfigHelper EOUltimatitaniumSet;
    public final EOMaterialConfigHelper EOUniversiumSet;
    public final EOMaterialConfigHelper EOUraniniteSet;
    public final EOMaterialConfigHelper EOUraniumSet;
    public final EOMaterialConfigHelper EOVanadiumSet;
    public final EOMaterialConfigHelper EOVividAlloySet;
    public final EOMaterialConfigHelper EOVoideriteSet;
    public final EOMaterialConfigHelper EOWarpedNetherWartSet;
    public final EOMaterialConfigHelper EOWoodenSet;
    public final EOMaterialConfigHelper EOWroughtIronSet;
    public final EOMaterialConfigHelper EOYttriumSet;
    public final EOMaterialConfigHelper EOZincSet;
    public final EOMaterialConfigHelper EOZirconSet;

    static {
        Pair<EOMaterialConfig, ModConfigSpec> pair = new ModConfigSpec.Builder().configure(EOMaterialConfig::new);
        CFG = pair.getLeft();
        CONFIG_SPEC = pair.getRight();
    }

    private EOMaterialConfig(ModConfigSpec.Builder builder) {
        builder.comment("""
                Eternal Ores Material Config.
                
                 This config allows you to Enable or Disable Eternal Ores material sets. These sets can be
                 disabled individually, or entirely.
                
                 This config DOES NOT unregister any of these material sets in any way, it only hides them and toggles any function they had, if they have one.
                
                 Each change requires a Game Restart.
                """).push("materials");

        this.EOAluminumSet = new EOMaterialConfigHelper("aluminum", EOMaterialConfigHelper.NATURAL_METAL_FEATURES);
        this.EOAlumiteSet = new EOMaterialConfigHelper("alumite", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOAmberSet = new EOMaterialConfigHelper("amber", EOMaterialConfigHelper.NATURAL_GEM_FEATURES);
        this.EOAmericiumSet = new EOMaterialConfigHelper("americium", EOMaterialConfigHelper.ALLOY_FEATURES_WITHOUT_GEAR);
        this.EOAmethystSet = new EOMaterialConfigHelper("amethyst", EOMaterialConfigHelper.VANILLA_GEM_FEATURES);
        this.EOAndesiteSet = new EOMaterialConfigHelper("andesite", EOMaterialConfigHelper.STONE_FEATURES);
        this.EOAnnealedCopperSet = new EOMaterialConfigHelper("annealed_copper", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOAnthraciteCoalSet = new EOMaterialConfigHelper("anthracite", EOMaterialConfigHelper.CARBON_FEATURES);
        this.EOAntimatterSet = new EOMaterialConfigHelper("antimatter", EOMaterialConfigHelper.BLOCK_ONLY);
        this.EOApatiteSet = new EOMaterialConfigHelper("apatite", EOMaterialConfigHelper.NATURAL_GEM_FEATURES);
        this.EOArcanumSet = new EOMaterialConfigHelper("arcanum", EOMaterialConfigHelper.UNNATURAL_GEM_FEATURES);
        this.EOArditeSet = new EOMaterialConfigHelper("ardite", EOMaterialConfigHelper.NATURAL_METAL_FEATURES);
        this.EOArmadilloSet = new EOMaterialConfigHelper("armadillo", EOMaterialConfigHelper.MOB_MATERIAL_MINIMUM);
        this.EOAuroriumSet = new EOMaterialConfigHelper("aurorium", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOBasaltSet = new EOMaterialConfigHelper("basalt", EOMaterialConfigHelper.STONE_FEATURES);
        this.EOBatteryAlloySet = new EOMaterialConfigHelper("battery_alloy", EOMaterialConfigHelper.ALLOY_FEATURES_WITHOUT_FOIL_GEAR);
        this.EOBerylliumSet = new EOMaterialConfigHelper("beryllium", EOMaterialConfigHelper.NATURAL_METAL_FEATURES);
        this.EOBiomassSet = new EOMaterialConfigHelper("biomass", EOMaterialConfigHelper.BIOMASS_FEATURE);
        this.EOBiosteelSet = new EOMaterialConfigHelper("biosteel", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOBismuthSet = new EOMaterialConfigHelper("bismuth", EOMaterialConfigHelper.ALLOY_FEATURES_WITHOUT_FOIL);
        this.EOBituminousCoalSet = new EOMaterialConfigHelper("bituminous", EOMaterialConfigHelper.CARBON_FEATURES);
        this.EOBlackBronzeSet = new EOMaterialConfigHelper("black_bronze", EOMaterialConfigHelper.ALLOY_FEATURES_WITHOUT_FOIL);
        this.EOBlackQuartzSet = new EOMaterialConfigHelper("black_quartz", EOMaterialConfigHelper.NATURAL_GEM_FEATURES);
        this.EOBlackSteelSet = new EOMaterialConfigHelper("black_steel", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOBlackstoneSet = new EOMaterialConfigHelper("blackstone", EOMaterialConfigHelper.STONE_FEATURES);
        this.EOBlazeSet = new EOMaterialConfigHelper("blaze", EOMaterialConfigHelper.MOB_MATERIAL_FEATURES);
        this.EOBlueSteelSet = new EOMaterialConfigHelper("blue_steel", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOBrassSet = new EOMaterialConfigHelper("brass", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOBrickSet = new EOMaterialConfigHelper("brick", EOMaterialConfigHelper.ONLY_DUST_FEATURES);
        this.EOBritanniaSilverSet = new EOMaterialConfigHelper("britannia_silver", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOBronzeSet = new EOMaterialConfigHelper("bronze", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOCadmiumSet = new EOMaterialConfigHelper("cadmium", EOMaterialConfigHelper.MINIMUM_FEATURES);
        this.EOCalciumSet = new EOMaterialConfigHelper("calcium", EOMaterialConfigHelper.MINIMUM_FEATURES);
        this.EOCalciteSet = new EOMaterialConfigHelper("calcite", EOMaterialConfigHelper.STONE_FEATURES);
        this.EOCaliforniumSet = new EOMaterialConfigHelper("californium", EOMaterialConfigHelper.MINIMUM_FEATURES);
        this.EOCatalyriumSet = new EOMaterialConfigHelper("catalyrium", EOMaterialConfigHelper.CATALYST_FEATURES);
        this.EOCastIronSet = new EOMaterialConfigHelper("cast_iron", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOCastSteelSet = new EOMaterialConfigHelper("cast_steel", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOCarbonBlend = new EOMaterialConfigHelper("carbon_blend", EOMaterialConfigHelper.BLEND_FEATURES);
        this.EOCeriumSet = new EOMaterialConfigHelper("cerium", EOMaterialConfigHelper.MINIMUM_FEATURES);
        this.EOCertusQuartzSet = new EOMaterialConfigHelper("certus_quartz", EOMaterialConfigHelper.UNNATURAL_GEM_FEATURES);
        this.EOCesiumSet = new EOMaterialConfigHelper("cesium", EOMaterialConfigHelper.METAL_WITHOUT_FEATURES);
        this.EOCharcoalSet = new EOMaterialConfigHelper("charcoal", EOMaterialConfigHelper.COKE_FEATURES);
        this.EOCinnabarSet = new EOMaterialConfigHelper("cinnabar", EOMaterialConfigHelper.NATURAL_GEM_FEATURES);
        this.EOClaySet = new EOMaterialConfigHelper("clay", EOMaterialConfigHelper.ONLY_DUST_FEATURES);
        this.EOCoalSet = new EOMaterialConfigHelper("coal", EOMaterialConfigHelper.CARBON_FEATURES);
        this.EOCobaltSet = new EOMaterialConfigHelper("cobalt", EOMaterialConfigHelper.NATURAL_METAL_FEATURES);
        this.EOCokeSet = new EOMaterialConfigHelper("coke", EOMaterialConfigHelper.COKE_FEATURES);
        this.EOConstantanSet = new EOMaterialConfigHelper("constantan", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOCopperSet = new EOMaterialConfigHelper("copper", EOMaterialConfigHelper.VANILLA_METAL_SPECIAL_FEATURES);
        this.EOCosmicMatterSet = new EOMaterialConfigHelper("cosmic_matter", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOChromiumSet = new EOMaterialConfigHelper("chromium", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOCrystallineAlloySet = new EOMaterialConfigHelper("crystalline_alloy", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOCupronickelSet = new EOMaterialConfigHelper("cupronickel", EOMaterialConfigHelper.ALLOY_FEATURES_WITHOUT_GEAR);
        this.EODeepslateSet = new EOMaterialConfigHelper("deepslate", EOMaterialConfigHelper.STONE_FEATURES);
        this.EODiamondSet = new EOMaterialConfigHelper("diamond", EOMaterialConfigHelper.VANILLA_GEM_FEATURES);
        this.EODioriteSet = new EOMaterialConfigHelper("diorite", EOMaterialConfigHelper.STONE_FEATURES);
        this.EODripstoneSet = new EOMaterialConfigHelper("dripstone", EOMaterialConfigHelper.ONLY_DUST_FEATURES);
        this.EODustSet = new EOMaterialConfigHelper("dust", EOMaterialConfigHelper.MINIMUM_FEATURES);
        this.EOElectrumSet = new EOMaterialConfigHelper("electrum", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOEmeraldSet = new EOMaterialConfigHelper("emerald", EOMaterialConfigHelper.VANILLA_GEM_FEATURES);
        this.EOEnergeticBlendSet = new EOMaterialConfigHelper("energetic_blend", EOMaterialConfigHelper.BLEND_FEATURES);
        this.EOEnderEyeSet = new EOMaterialConfigHelper("ender_eye", EOMaterialConfigHelper.BLOCK_ONLY);
        this.EOEndergeticSet = new EOMaterialConfigHelper("endergetic_blend", EOMaterialConfigHelper.BLEND_FEATURES);
        this.EOEnderPearlSet = new EOMaterialConfigHelper("ender", EOMaterialConfigHelper.MOB_MATERIAL_FEATURES);
        this.EOEnderiumSet = new EOMaterialConfigHelper("enderium", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOEndstoneSet = new EOMaterialConfigHelper("endstone", EOMaterialConfigHelper.STONE_FEATURES);
        this.EOEnergeticSilverSet = new EOMaterialConfigHelper("energetic_silver", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOEternalDarkSet = new EOMaterialConfigHelper("eternal_dark", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOEternalLightSet = new EOMaterialConfigHelper("eternal_light", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOEternitySet = new EOMaterialConfigHelper("eternity", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOEtheriumSet = new EOMaterialConfigHelper("etherium", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOExoticMatterSet = new EOMaterialConfigHelper("exotic_matter", EOMaterialConfigHelper.BLOCK_ONLY);
        this.EOFlintSet = new EOMaterialConfigHelper("flint", EOMaterialConfigHelper.MINIMUM_FEATURES_BLOCK);
        this.EOFluixSet = new EOMaterialConfigHelper("fluix", EOMaterialConfigHelper.UNNATURAL_GEM_FEATURES);
        this.EOFluoriteSet = new EOMaterialConfigHelper("fluorite", EOMaterialConfigHelper.HALIDE_FEATURES);
        this.EOFranciumSet = new EOMaterialConfigHelper("francium", EOMaterialConfigHelper.METAL_WITHOUT_FEATURES);
        this.EOGalliumSet = new EOMaterialConfigHelper("gallium", EOMaterialConfigHelper.NATURAL_METAL_FEATURES);
        this.EOGarnetSet = new EOMaterialConfigHelper("garnet", EOMaterialConfigHelper.NATURAL_GEM_FEATURES);
        this.EOGoldSet = new EOMaterialConfigHelper("gold", EOMaterialConfigHelper.VANILLA_METAL_FEATURES);
        this.EOGraphiteSet = new EOMaterialConfigHelper("graphite", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOGraniteSet = new EOMaterialConfigHelper("granite", EOMaterialConfigHelper.STONE_FEATURES);
        this.EOGravelSet = new EOMaterialConfigHelper("gravel", EOMaterialConfigHelper.ONLY_DUST_FEATURES);
        this.EOGravitroniumSet = new EOMaterialConfigHelper("gravitronium", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOHCarbonBlend = new EOMaterialConfigHelper("he_carbon_blend", EOMaterialConfigHelper.BLEND_FEATURES);
        this.EOHafniumSet = new EOMaterialConfigHelper("hafnium", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOHepatizonSet = new EOMaterialConfigHelper("hepatizon", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOIndiumSet = new EOMaterialConfigHelper("indium", EOMaterialConfigHelper.METAL_WITHOUT_FEATURES);
        this.EOInvarSet = new EOMaterialConfigHelper("invar", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOIridiumSet = new EOMaterialConfigHelper("iridium", EOMaterialConfigHelper.NATURAL_METAL_FEATURES);
        this.EOIronSet = new EOMaterialConfigHelper("iron", EOMaterialConfigHelper.VANILLA_METAL_FEATURES);
        this.EOJadeSet = new EOMaterialConfigHelper("jade", EOMaterialConfigHelper.NATURAL_GEM_FEATURES);
        this.EOKanthalSet = new EOMaterialConfigHelper("kanthal", EOMaterialConfigHelper.ALLOY_FEATURES_WITHOUT_FOIL_GEAR);
        this.EOLapisSet = new EOMaterialConfigHelper("lapis", EOMaterialConfigHelper.VANILLA_GEM_FEATURES);
        this.EOLCarbonBlend = new EOMaterialConfigHelper("le_carbon_blend", EOMaterialConfigHelper.BLEND_FEATURES);
        this.EOLeadSet = new EOMaterialConfigHelper("lead", EOMaterialConfigHelper.NATURAL_METAL_FEATURES);
        this.EOLigniteCoalSet = new EOMaterialConfigHelper("lignite", EOMaterialConfigHelper.CARBON_FEATURES);
        this.EOLumiumSet = new EOMaterialConfigHelper("lumium", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOMagnesiumSet = new EOMaterialConfigHelper("magnesium", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOManganeseSet = new EOMaterialConfigHelper("manganese", EOMaterialConfigHelper.ALLOY_FEATURES_WITHOUT_GEAR);
        this.EOMelodicAlloySet = new EOMaterialConfigHelper("melodic_alloy", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOMissingSet = new EOMaterialConfigHelper("missing", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOModulariumSet = new EOMaterialConfigHelper("modularium", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOMolybdenumSet = new EOMaterialConfigHelper("molybdenum", EOMaterialConfigHelper.NATURAL_METAL_FEATURES);
        this.EOMonaziteSet = new EOMaterialConfigHelper("monazite", EOMaterialConfigHelper.NATURAL_GEM_FEATURES);
        this.EOMorphiteSet = new EOMaterialConfigHelper("morphite", EOMaterialConfigHelper.UNNATURAL_GEM_FEATURES);
        this.EONaniteSet = new EOMaterialConfigHelper("nanite", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EONautilusSet = new EOMaterialConfigHelper("nautilus", EOMaterialConfigHelper.MOB_MATERIAL_MINIMUM);
        this.EONecroticariteSet = new EOMaterialConfigHelper("necroticarite", EOMaterialConfigHelper.NATURAL_GEM_FEATURES);
        this.EONeptuniumSet = new EOMaterialConfigHelper("neptunium", EOMaterialConfigHelper.ALLOY_FEATURES_WITHOUT_GEAR);
        this.EONetherBlendSet = new EOMaterialConfigHelper("nether_blend", EOMaterialConfigHelper.BLEND_FEATURES);
        this.EONetherBrickSet = new EOMaterialConfigHelper("nether_brick", EOMaterialConfigHelper.ONLY_DUST_FEATURES);
        this.EONetherStarSet = new EOMaterialConfigHelper("nether_star", EOMaterialConfigHelper.MOB_MATERIAL_FEATURES);
        this.EONetherWartSet = new EOMaterialConfigHelper("nether_wart", EOMaterialConfigHelper.ONLY_DUST_FEATURES);
        this.EONetheriteSet = new EOMaterialConfigHelper("netherite", EOMaterialConfigHelper.NETHERITE_FEATURES);
        this.EONetherrackSet = new EOMaterialConfigHelper("netherrack", EOMaterialConfigHelper.STONE_FEATURES);
        this.EONethersteelSet = new EOMaterialConfigHelper("nethersteel", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EONeodymiumSet = new EOMaterialConfigHelper("neodymium", EOMaterialConfigHelper.NATURAL_METAL_FEATURES_GEAR_FOILESS);
        this.EONickelSet = new EOMaterialConfigHelper("nickel", EOMaterialConfigHelper.NATURAL_METAL_FEATURES);
        this.EONiobiumSet = new EOMaterialConfigHelper("niobium", EOMaterialConfigHelper.METAL_WITHOUT_FEATURES);
        this.EONiterSet = new EOMaterialConfigHelper("niter", EOMaterialConfigHelper.GEO_FEATURES);
        this.EONovalloySet = new EOMaterialConfigHelper("novalloy", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOsgloglasSet = new EOMaterialConfigHelper("osgloglass", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EObsidianSet = new EOMaterialConfigHelper("obsidian", EOMaterialConfigHelper.NATURAL_GEM_FEATURES);
        this.EOOsmiumSet = new EOMaterialConfigHelper("osmium", EOMaterialConfigHelper.NATURAL_METAL_FEATURES);
        this.EOnyxSet = new EOMaterialConfigHelper("onyx", EOMaterialConfigHelper.NATURAL_GEM_FEATURES);
        this.EOPalladiumSet = new EOMaterialConfigHelper("palladium", EOMaterialConfigHelper.NATURAL_METAL_FEATURES);
        this.EOPeatCoalSet = new EOMaterialConfigHelper("peat", EOMaterialConfigHelper.CARBON_FEATURES);
        this.EOPearlSet = new EOMaterialConfigHelper("pearl", EOMaterialConfigHelper.NATURAL_GEM_FEATURES);
        this.EOPeridotSet = new EOMaterialConfigHelper("peridot", EOMaterialConfigHelper.NATURAL_GEM_FEATURES);
        this.EOPewterSet = new EOMaterialConfigHelper("pewter", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOPhantomMembraneSet = new EOMaterialConfigHelper("phantom_membrane", EOMaterialConfigHelper.BLOCK_ONLY);
        this.EOPhosphorusSet = new EOMaterialConfigHelper("phosphorus", EOMaterialConfigHelper.MINIMUM_FEATURES);
        this.EOPigIronSet = new EOMaterialConfigHelper("pig_iron", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOPlatinumSet = new EOMaterialConfigHelper("platinum", EOMaterialConfigHelper.NATURAL_METAL_FEATURES);
        this.EOPlutoniumSet = new EOMaterialConfigHelper("plutonium", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOPrimorniumSet = new EOMaterialConfigHelper("primornium", EOMaterialConfigHelper.UNNATURAL_GEM_FEATURES);
        this.EOPrismarineSet = new EOMaterialConfigHelper("prismarine", EOMaterialConfigHelper.VANILLA_GEM_FEATURES_BLOCK);
        this.EOPurpurSet = new EOMaterialConfigHelper("purpur", EOMaterialConfigHelper.ONLY_DUST_FEATURES);
        this.EOPyroliteSet = new EOMaterialConfigHelper("pyrolite", EOMaterialConfigHelper.NATURAL_GEM_FEATURES);
        this.EOQuantiquariteSet = new EOMaterialConfigHelper("quantiquarite", EOMaterialConfigHelper.UNNATURAL_GEM_FEATURES);
        this.EOQuartzSet = new EOMaterialConfigHelper("quartz", EOMaterialConfigHelper.VANILLA_GEM_FEATURES);
        this.EOQuartzEnrichedCopperSet = new EOMaterialConfigHelper("quartz_enriched_copper", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOQuartzEnrichedIronSet = new EOMaterialConfigHelper("quartz_enriched_iron", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EORareEarthSet = new EOMaterialConfigHelper("rare_earth", EOMaterialConfigHelper.MINIMUM_FEATURES);
        this.EORedstoneSet = new EOMaterialConfigHelper("redstone", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EORedSandSet = new EOMaterialConfigHelper("red_sand", EOMaterialConfigHelper.ONLY_DUST_FEATURES);
        this.EORedSteelSet = new EOMaterialConfigHelper("red_steel", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EORhodiumSet = new EOMaterialConfigHelper("rhodium", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EORoseGoldSet = new EOMaterialConfigHelper("rose_gold", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EORottenFleshSet = new EOMaterialConfigHelper("rotten_flesh", EOMaterialConfigHelper.BLOCK_ONLY);
        this.EORubidiumSet = new EOMaterialConfigHelper("rubidium", EOMaterialConfigHelper.METAL_WITHOUT_FEATURES);
        this.EORubySet = new EOMaterialConfigHelper("ruby", EOMaterialConfigHelper.NATURAL_GEM_FEATURES);
        this.EORutheniumSet = new EOMaterialConfigHelper("ruthenium", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOSaltSet = new EOMaterialConfigHelper("salt", EOMaterialConfigHelper.SALT_FEATURES);
        this.EOSamariumSet = new EOMaterialConfigHelper("samarium", EOMaterialConfigHelper.ALLOY_FEATURES_WITHOUT_GEAR);
        this.EOSandSet = new EOMaterialConfigHelper("sand", EOMaterialConfigHelper.ONLY_DUST_FEATURES);
        this.EOSanguisVivusSet = new EOMaterialConfigHelper("sanguis_vivus", EOMaterialConfigHelper.UNNATURAL_GEM_FEATURES);
        this.EOSapphireSet = new EOMaterialConfigHelper("sapphire", EOMaterialConfigHelper.NATURAL_GEM_FEATURES);
        this.EOSculkSet = new EOMaterialConfigHelper("sculk", EOMaterialConfigHelper.MINIMUM_FEATURES);
        this.EOSculkiteSet = new EOMaterialConfigHelper("sculkite", EOMaterialConfigHelper.NATURAL_METAL_FEATURES);
        this.EOSeleniumSet = new EOMaterialConfigHelper("selenium", EOMaterialConfigHelper.MINIMUM_FEATURES);
        this.EOShadowBlendSet = new EOMaterialConfigHelper("shadow_blend", EOMaterialConfigHelper.BLEND_FEATURES);
        this.EOShadowsteelSet = new EOMaterialConfigHelper("shadowsteel", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOShulkerSet = new EOMaterialConfigHelper("shulker", EOMaterialConfigHelper.ONLY_DUST_FEATURES);
        this.EOSignalumSet = new EOMaterialConfigHelper("signalum", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOSiliconSet = new EOMaterialConfigHelper("silicon", EOMaterialConfigHelper.SILICON_FEATURES);
        this.EOSilverSet = new EOMaterialConfigHelper("silver", EOMaterialConfigHelper.NATURAL_METAL_FEATURES);
        this.EOSoulSandSet = new EOMaterialConfigHelper("soul_sand", EOMaterialConfigHelper.MINIMUM_FEATURES);
        this.EOSourceSet = new EOMaterialConfigHelper("source", EOMaterialConfigHelper.UNNATURAL_GEM_FEATURES);
        this.EOSpectralSkyBlueriteSet = new EOMaterialConfigHelper("spectral_sky_bluerite", EOMaterialConfigHelper.UNNATURAL_GEM_FEATURES);
        this.EOSpinelSet = new EOMaterialConfigHelper("spinel", EOMaterialConfigHelper.NATURAL_GEM_FEATURES);
        this.EOStainlessSteelSet = new EOMaterialConfigHelper("stainless_steel", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOStellariumSet = new EOMaterialConfigHelper("stellarium", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOStellarAlloySet = new EOMaterialConfigHelper("stellar_alloy", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOSteelSet = new EOMaterialConfigHelper("steel", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOStoneSet = new EOMaterialConfigHelper("stone", EOMaterialConfigHelper.STONE_FEATURES);
        this.EOStrangeMatterSet = new EOMaterialConfigHelper("strange_matter", EOMaterialConfigHelper.BLOCK_ONLY);
        this.EOSugarSet = new EOMaterialConfigHelper("sugar", EOMaterialConfigHelper.BLOCK_ONLY);
        this.EOSulfurSet = new EOMaterialConfigHelper("sulfur", EOMaterialConfigHelper.SULFUR_FEATURES);
        this.EOTachyariteSet = new EOMaterialConfigHelper("tachyarite", EOMaterialConfigHelper.UNNATURAL_GEM_FEATURES);
        this.EOTantalumSet = new EOMaterialConfigHelper("tantalum", EOMaterialConfigHelper.ALLOY_FEATURES_WITHOUT_PLATE_ROD);
        this.EOTanzaniteSet = new EOMaterialConfigHelper("tanzanite", EOMaterialConfigHelper.NATURAL_GEM_FEATURES);
        this.EOTemictetlSet = new EOMaterialConfigHelper("temictetl", EOMaterialConfigHelper.UNNATURAL_GEM_FEATURES);
        this.EOTinSet = new EOMaterialConfigHelper("tin", EOMaterialConfigHelper.NATURAL_METAL_FEATURES);
        this.EOTitaniumSet = new EOMaterialConfigHelper("titanium", EOMaterialConfigHelper.NATURAL_METAL_FEATURES);
        this.EOTuffSet = new EOMaterialConfigHelper("tuff", EOMaterialConfigHelper.STONE_FEATURES);
        this.EOTungstenSet = new EOMaterialConfigHelper("tungsten", EOMaterialConfigHelper.NATURAL_METAL_FEATURES);
        this.EOTurtleSet = new EOMaterialConfigHelper("turtle", EOMaterialConfigHelper.MOB_MATERIAL_MINIMUM);
        this.EOUnstableIngotSet = new EOMaterialConfigHelper("unstable", EOMaterialConfigHelper.UNSTABLE_SET);
        this.EOUltimatitaniumSet = new EOMaterialConfigHelper("ultimatitanium", EOMaterialConfigHelper.NATURAL_METAL_FEATURES);
        this.EOUniversiumSet = new EOMaterialConfigHelper("universium", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOUraniniteSet = new EOMaterialConfigHelper("uraninite", EOMaterialConfigHelper.NATURAL_METAL_FEATURES_WITH_ITEM);
        this.EOUraniumSet = new EOMaterialConfigHelper("uranium", EOMaterialConfigHelper.NATURAL_METAL_FEATURES);
        this.EOVanadiumSet = new EOMaterialConfigHelper("vanadium", EOMaterialConfigHelper.NATURAL_METAL_FEATURES);
        this.EOVividAlloySet = new EOMaterialConfigHelper("vivid_alloy", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOVoideriteSet = new EOMaterialConfigHelper("voiderite", EOMaterialConfigHelper.UNNATURAL_GEM_FEATURES);
        this.EOWarpedNetherWartSet = new EOMaterialConfigHelper("warped_nether", EOMaterialConfigHelper.ONLY_DUST_FEATURES);
        this.EOWoodenSet = new EOMaterialConfigHelper("wood", EOMaterialConfigHelper.WOODEN_FEATURES);
        this.EOWroughtIronSet = new EOMaterialConfigHelper("wrought_iron", EOMaterialConfigHelper.ALLOY_FEATURES);
        this.EOYttriumSet = new EOMaterialConfigHelper("yttrium", EOMaterialConfigHelper.METAL_WITHOUT_FEATURES);
        this.EOZincSet = new EOMaterialConfigHelper("zinc", EOMaterialConfigHelper.NATURAL_METAL_FEATURES);
        this.EOZirconSet = new EOMaterialConfigHelper("zircon", EOMaterialConfigHelper.NATURAL_GEM_FEATURES);

        this.EOAluminumSet.configure(builder);
        this.EOAlumiteSet.configure(builder);
        this.EOAmberSet.configure(builder);
        this.EOAmericiumSet.configure(builder);
        this.EOAmethystSet.configure(builder);
        this.EOAndesiteSet.configure(builder);
        this.EOAnnealedCopperSet.configure(builder);
        this.EOAnthraciteCoalSet.configure(builder);
        this.EOAntimatterSet.configure(builder);
        this.EOApatiteSet.configure(builder);
        this.EOArcanumSet.configure(builder);
        this.EOArditeSet.configure(builder);
        this.EOArmadilloSet.configure(builder);
        this.EOAuroriumSet.configure(builder);
        this.EOBasaltSet.configure(builder);
        this.EOBatteryAlloySet.configure(builder);
        this.EOBerylliumSet.configure(builder);
        this.EOBiomassSet.configure(builder);
        this.EOBiosteelSet.configure(builder);
        this.EOBismuthSet.configure(builder);
        this.EOBituminousCoalSet.configure(builder);
        this.EOBlackBronzeSet.configure(builder);
        this.EOBlackQuartzSet.configure(builder);
        this.EOBlackSteelSet.configure(builder);
        this.EOBlackstoneSet.configure(builder);
        this.EOBlazeSet.configure(builder);
        this.EOBlueSteelSet.configure(builder);
        this.EOBrassSet.configure(builder);
        this.EOBrickSet.configure(builder);
        this.EOBritanniaSilverSet.configure(builder);
        this.EOBronzeSet.configure(builder);
        this.EOCadmiumSet.configure(builder);
        this.EOCalciumSet.configure(builder);
        this.EOCalciteSet.configure(builder);
        this.EOCaliforniumSet.configure(builder);
        this.EOCatalyriumSet.configure(builder);
        this.EOCastIronSet.configure(builder);
        this.EOCastSteelSet.configure(builder);
        this.EOCarbonBlend.configure(builder);
        this.EOCeriumSet.configure(builder);
        this.EOCertusQuartzSet.configure(builder);
        this.EOCesiumSet.configure(builder);
        this.EOCharcoalSet.configure(builder);
        this.EOCinnabarSet.configure(builder);
        this.EOClaySet.configure(builder);
        this.EOCoalSet.configure(builder);
        this.EOCobaltSet.configure(builder);
        this.EOCokeSet.configure(builder);
        this.EOConstantanSet.configure(builder);
        this.EOCopperSet.configure(builder);
        this.EOCosmicMatterSet.configure(builder);
        this.EOChromiumSet.configure(builder);
        this.EOCrystallineAlloySet.configure(builder);
        this.EOCupronickelSet.configure(builder);
        this.EODeepslateSet.configure(builder);
        this.EODiamondSet.configure(builder);
        this.EODioriteSet.configure(builder);
        this.EODripstoneSet.configure(builder);
        this.EODustSet.configure(builder);
        this.EOElectrumSet.configure(builder);
        this.EOEmeraldSet.configure(builder);
        this.EOEnergeticBlendSet.configure(builder);
        this.EOEnderEyeSet.configure(builder);
        this.EOEnderPearlSet.configure(builder);
        this.EOEndergeticSet.configure(builder);
        this.EOEnderiumSet.configure(builder);
        this.EOEndstoneSet.configure(builder);
        this.EOEnergeticSilverSet.configure(builder);
        this.EOEternalDarkSet.configure(builder);
        this.EOEternalLightSet.configure(builder);
        this.EOEternitySet.configure(builder);
        this.EOEtheriumSet.configure(builder);
        this.EOExoticMatterSet.configure(builder);
        this.EOFlintSet.configure(builder);
        this.EOFluixSet.configure(builder);
        this.EOFluoriteSet.configure(builder);
        this.EOFranciumSet.configure(builder);
        this.EOGalliumSet.configure(builder);
        this.EOGarnetSet.configure(builder);
        this.EOGoldSet.configure(builder);
        this.EOGraphiteSet.configure(builder);
        this.EOGraniteSet.configure(builder);
        this.EOGravelSet.configure(builder);
        this.EOGravitroniumSet.configure(builder);
        this.EOHCarbonBlend.configure(builder);
        this.EOHafniumSet.configure(builder);
        this.EOHepatizonSet.configure(builder);
        this.EOIndiumSet.configure(builder);
        this.EOInvarSet.configure(builder);
        this.EOIridiumSet.configure(builder);
        this.EOIronSet.configure(builder);
        this.EOJadeSet.configure(builder);
        this.EOKanthalSet.configure(builder);
        this.EOLapisSet.configure(builder);
        this.EOLCarbonBlend.configure(builder);
        this.EOLeadSet.configure(builder);
        this.EOLigniteCoalSet.configure(builder);
        this.EOLumiumSet.configure(builder);
        this.EOMagnesiumSet.configure(builder);
        this.EOManganeseSet.configure(builder);
        this.EOMelodicAlloySet.configure(builder);
        this.EOMissingSet.configure(builder);
        this.EOModulariumSet.configure(builder);
        this.EOMolybdenumSet.configure(builder);
        this.EOMonaziteSet.configure(builder);
        this.EOMorphiteSet.configure(builder);
        this.EONaniteSet.configure(builder);
        this.EONautilusSet.configure(builder);
        this.EONecroticariteSet.configure(builder);
        this.EONeptuniumSet.configure(builder);
        this.EONetherBlendSet.configure(builder);
        this.EONetherBrickSet.configure(builder);
        this.EONetherStarSet.configure(builder);
        this.EONetherWartSet.configure(builder);
        this.EONetheriteSet.configure(builder);
        this.EONetherrackSet.configure(builder);
        this.EONethersteelSet.configure(builder);
        this.EONeodymiumSet.configure(builder);
        this.EONickelSet.configure(builder);
        this.EONiobiumSet.configure(builder);
        this.EONiterSet.configure(builder);
        this.EONovalloySet.configure(builder);
        this.EOsgloglasSet.configure(builder);
        this.EObsidianSet.configure(builder);
        this.EOOsmiumSet.configure(builder);
        this.EOnyxSet.configure(builder);
        this.EOPalladiumSet.configure(builder);
        this.EOPeatCoalSet.configure(builder);
        this.EOPearlSet.configure(builder);
        this.EOPeridotSet.configure(builder);
        this.EOPewterSet.configure(builder);
        this.EOPhantomMembraneSet.configure(builder);
        this.EOPhosphorusSet.configure(builder);
        this.EOPigIronSet.configure(builder);
        this.EOPlatinumSet.configure(builder);
        this.EOPlutoniumSet.configure(builder);
        this.EOPrimorniumSet.configure(builder);
        this.EOPrismarineSet.configure(builder);
        this.EOPurpurSet.configure(builder);
        this.EOPyroliteSet.configure(builder);
        this.EOQuantiquariteSet.configure(builder);
        this.EOQuartzSet.configure(builder);
        this.EOQuartzEnrichedCopperSet.configure(builder);
        this.EOQuartzEnrichedIronSet.configure(builder);
        this.EORareEarthSet.configure(builder);
        this.EORedstoneSet.configure(builder);
        this.EORedSandSet.configure(builder);
        this.EORedSteelSet.configure(builder);
        this.EORhodiumSet.configure(builder);
        this.EORoseGoldSet.configure(builder);
        this.EORottenFleshSet.configure(builder);
        this.EORubidiumSet.configure(builder);
        this.EORubySet.configure(builder);
        this.EORutheniumSet.configure(builder);
        this.EOSaltSet.configure(builder);
        this.EOSamariumSet.configure(builder);
        this.EOSandSet.configure(builder);
        this.EOSanguisVivusSet.configure(builder);
        this.EOSapphireSet.configure(builder);
        this.EOSculkSet.configure(builder);
        this.EOSculkiteSet.configure(builder);
        this.EOSeleniumSet.configure(builder);
        this.EOShadowBlendSet.configure(builder);
        this.EOShadowsteelSet.configure(builder);
        this.EOShulkerSet.configure(builder);
        this.EOSignalumSet.configure(builder);
        this.EOSiliconSet.configure(builder);
        this.EOSilverSet.configure(builder);
        this.EOSoulSandSet.configure(builder);
        this.EOSourceSet.configure(builder);
        this.EOSpectralSkyBlueriteSet.configure(builder);
        this.EOSpinelSet.configure(builder);
        this.EOStainlessSteelSet.configure(builder);
        this.EOStellariumSet.configure(builder);
        this.EOStellarAlloySet.configure(builder);
        this.EOSteelSet.configure(builder);
        this.EOStoneSet.configure(builder);
        this.EOStrangeMatterSet.configure(builder);
        this.EOSugarSet.configure(builder);
        this.EOSulfurSet.configure(builder);
        this.EOTachyariteSet.configure(builder);
        this.EOTantalumSet.configure(builder);
        this.EOTanzaniteSet.configure(builder);
        this.EOTemictetlSet.configure(builder);
        this.EOTinSet.configure(builder);
        this.EOTitaniumSet.configure(builder);
        this.EOTuffSet.configure(builder);
        this.EOTungstenSet.configure(builder);
        this.EOTurtleSet.configure(builder);
        this.EOUnstableIngotSet.configure(builder);
        this.EOUltimatitaniumSet.configure(builder);
        this.EOUniversiumSet.configure(builder);
        this.EOUraniniteSet.configure(builder);
        this.EOUraniumSet.configure(builder);
        this.EOVanadiumSet.configure(builder);
        this.EOVividAlloySet.configure(builder);
        this.EOVoideriteSet.configure(builder);
        this.EOWarpedNetherWartSet.configure(builder);
        this.EOWoodenSet.configure(builder);
        this.EOWroughtIronSet.configure(builder);
        this.EOYttriumSet.configure(builder);
        this.EOZincSet.configure(builder);
        this.EOZirconSet.configure(builder);
        builder.pop();
    }
}
